dbc_file: pixmoving.dbc
protocol_conf: pixmoving.yml
car_type: hooke 
sender_list: [DriveCtrl, BrakeCtrl, SteerCtrl, VehicleCtrl, WheelCtrl]
sender: ACU
black_list: []

output_dir: output
config_dir: config/

