Header header 
# 风机速度控制 [rpm] [0|0]
int32 FanSpeedCtrl 
#  [] [0|1]
int8 ShakerDusterCtrl 
# 喷雾降尘 [] [0|1]
int8 DedustingCtrl 
# 一键清扫控制 [] [0|3]
int8 AutoCleaningStartCtrl 
# 一键倾倒 [] [0|3]
int8 AutoGarbageDumpStartCtrl 
# 吸盘升降控制 [] [0|3]
int8 MouthpieceUpDownCtrl 
# 扫盘升降 [] [0|3]
int8 SweepPlateUpDown 
# 风机工作模式 [] [0|3]
int8 FanModeCtrl 
# 风机速度模式 [] [0|1]
int8 FanSpeedMode 
# 扫盘转速挡位控制 [] [0|3]
int8 SweepModeCtrl 
# 割草转速挡位控制 [] [0|3]
int8 MowingSpeedCtrl 
