Header header 
#  [] [0|0]
bool BMS_CommunicationFault 
#  [] [0|0]
bool ChassisEmergencySta 
#  [] [0|0]
bool LeadacidBatteryLow 
#  [] [0|0]
bool ControlerCommunicationFault 
#  [] [0|0]
bool ChassisCrashSta 
#  [] [0|0]
bool EPS_RearCommunicationFault 
#  [] [0|0]
bool EPS_FrontCommunicationFault 
#  [] [0|0]
bool EDS_RrCommunicationFault 
#  [] [0|0]
bool EDS_RfCommunicationFault 
#  [] [0|0]
bool EDS_LrCommunicationFault 
#  [] [0|0]
bool EDS_LfCommunicationFault 
#  [] [0|0]
bool EBS_CommunicationFault 
#  [] [0|0]
int32 ChassisVcuOtherErr 
