Header header 
#  [] [0|0]
int8 CarWork_State 
#  [] [0|0]
int8 CarPower_State 
#  [] [0|0]
int8 Headlight_Actual 
#  [] [0|1]
int8 AEB_Trigger_State 
#  [] [0|1]
int8 Brake_LightActual 
#  [] [0|0]
int8 TurnLight_Actual 
#  [] [0|255]
int32 Vehicle_Errcode 
#  [] [0|7]
int8 Drive_ModeStatus 
#  [] [0|7]
int8 Steer_ModeStatus 
#  [] [0|0]
int8 Vehicle_ModeState 
#  [] [0|0]
int8 Vehicle_FrontCrashState 
#  [] [0|0]
int8 BackCrash_State 
#  [] [0|0]
int8 AEB_BrakeState 
#  [m/s^2] [-10|10]
float32 Vehicle_Acc 
#  [m/s] [-32.768|32.767]
float32 Vehicle_Speed 
